- name: Install Terraform and Git
  hosts: all
  tasks:
    - name: Download Terraform
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
        dest: "/home/azureuser/ansible/terraform.zip"
        mode: '0644'  # Optional: Ensure proper file permissions
      
    - name: Extract Terraform
      ansible.builtin.unarchive:
        src: "/home/azureuser/ansible/terraform.zip"
        dest: "/home/azureuser/ansible"
        remote_src: yes

    - name: Verify Terraform Installation
      ansible.builtin.command: "/home/azureuser/ansible/terraform --version"
      register: terraform_version

    - name: Display Terraform Version
      ansible.builtin.debug:
        var: terraform_version.stdout

